/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzq_ndktest_Load */

#ifndef _Included_com_lzq_ndktest_Load
#define _Included_com_lzq_ndktest_Load
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzq_ndktest_Load
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lzq_ndktest_Load_addInt
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
